apiVersion: v1
kind: Service
metadata:
  name: tms-service
  labels:
    app: tms-deployment
spec:
  type: NodePort
  selector:
    app: tms-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31100
